version: '3'

services:
  app-test:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      # - LETSENCRYPT_EMAIL=your.email@domain.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
