version: '3'

services:
  my-app:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=pedidostdf.com.ar
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pedidostdf.com.ar
      - LETSENCRYPT_EMAIL=liderclick.oficial@gmail.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80

networks:
  proxy:
    external:
      name: nginx-proxy
