version: '3'

services:
  my-app:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80
    networks:
      - web-network
      - nginx-proxy

networks:
  web-network:
    driver: bridge
  nginx-proxy:
    external: true