version: '3'

services:
  my-app:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL={LETSENCRYPT_EMAIL}
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80
    networks:
      - nginx-proxy

networks:
  default:
    external:
      name: nginx-proxy
